all: execl execv execlp execvp execle execve

execl.o: execl.c
	gcc -c execl.c

execv.o: execv.c
	gcc -c execv.c

execlp.o: execlp.c
	gcc -c execlp.c

execvp.o: execvp.c
	gcc -c execvp.c

execle.o: execle.c
	gcc -c execle.c

execve.o: execve.c
	gcc -c execve.c

clean:
	rm -rf *.o execl execv execlp execvp execle execve

